export const styles = {
    syncBtn:{
      height:'55px', 
      lineHeight:'50px', 
      margin:0, 
      padding:'10px', 
      backgroundColor:'#5dbede',
      color:'white',
      "&:hover":{
          color:'#5dbede',
          backgroundColor:'#efefef'
      }
    },
    paper:{
      position:'relative'
    },
    taskIcons:{
      position:'absolute',
      top:'14px',
      right:'5px',
    },
    text:{
      fontSize:'20px',
      fontWeight:500
    },
    box:{
      display:'flex',
      alignItems:'center'
    }

}