export const styles= {
    container:{
      display:'flex',
      alignItems:'center',
      justifyContent:'space-between',
    },
    text:{
      fontSize:'20px',
      fontWeight:500
    },
    linkBtn:{
      fontSize:'16px'
    },
    
    box:{
      display:'flex',
      alignItems:'center'
    }, 
    error:{
      display:'flex',
      fontWeight:'bold',
      fontSize:'22px',
      textAlign:'center',
      justifyContent:'center',
      paddingTop:'22px'
    },
    loading:{
      display:'flex',
      fontSize:'22px',
      textAlign:'center',
      justifyContent:'center',
      paddingTop:'22px'
    },
    div:{
      display:'flex', 
      justifyContent:'space-between',
      alignItems:'center',
      height:'50px'
     },
     icon:{
          fontSize:'26px'
      },
      taskContainer:{
        display:'flex',
      alignItems:'center',
      justifyContent:'space-between',
      mb:2
    },
    Editcontainer:{
      position:'relative', 
      mb:3,
      padding:0
  },
  input:{
      height:'30px', 
      width:'80%', 
      transform:"translateX('32323px')",
      padding:0, 
      lineHeight:'30px', 
      border:'none',
  },
  saveEditbtn:{
      position:'absolute', 
      height:'55px', 
      lineHeight:'50px', 
      right:0, 
      top:0, 
      margin:0, 
      padding:0, 
      width:'20%',
      backgroundColor:'#5dbede',
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 0,
      color:'white',
      "&:hover":{
          color:'#5dbede',
          backgroundColor:'#efefef'
      }
  },
  helperTextEdit:{
    position:'absolute',
        left:0,
        top:'50px',
        color:'rgba(0,0,0,0.5)'
  }
  }